name: Docker Hub CI/CD for Velo-Tick API

on:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP 8.2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      # Install dependencies
      - name: Install Composer Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      # Debug: List backend directory
      - name: List backend directory
        run: ls -l

      # Run tests (optional, uncomment if you want tests)
      # - name: Run Tests
      #   run: php artisan test

      # Save the build artifact for the next job
      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: velotick-backend
          path: .
  
  docker:
    runs-on: ubuntu-latest
    needs: build

    defaults:
      run:
        working-directory: ./backend

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Download the build artifact from the previous job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: velotick-backend
          path: backend

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/velotick-backend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/velotick-backend:${{ github.sha }}
